version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      POSTGRES_DB: drupal

  www:
    depends_on:
      - db
    image: farmos/farmos:3.x-dev
    volumes:
      - './www:/opt/drupal'
    ports:
      - '80:80'
